require("dotenv").config();

module.exports = {
    VITE_FRONTEND_URL_DEVELOPMENT: process.env.VITE_FRONTEND_URL_DEVELOPMENT,
    VITE_FRONTEND_URL_PRODUCTION: process.env.VITE_FRONTEND_URL_PRODUCTION,
    VITE_FRONTEND_PORT: process.env.VITE_FRONTEND_PORT,

    DB_NAME_DEV: process.env.DB_NAME_DEV,
    DB_NAME: process.env.DB_NAME,
    DB_USER: process.env.DB_USER,
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_PORT: process.env.DB_PORT,
    DB_HOST: process.env.DB_HOST,
    DB_SSL_MODE: process.env.DB_SSL_MODE,

    JWT_SECRET: process.env.JWT_SECRET,

    SHARED_API_KEY: process.env.SHARED_API_KEY,
    ID_PREFIX: process.env.ID_PREFIX,
    ID_LENGTH: process.env.ID_LENGTH,

    EMPLOYEE_MANAGEMENT: process.env.EMPLOYEE_MANAGEMENT,
    VITE_FRONTEND_PAYROLL_URL_PRODUCTION: process.env.VITE_FRONTEND_PAYROLL_URL_PRODUCTION,
    VITE_FRONTEND_PAYROLL_URL_DEVELOPMENT: process.env.VITE_FRONTEND_PAYROLL_URL_DEVELOPMENT,

    VITE_FRONTEND_URL_DEVELOPMENT_SL: process.env.VITE_FRONTEND_URL_DEVELOPMENT_SL,
    VITE_FRONTEND_URL_PRODUCTION_SL: process.env.VITE_FRONTEND_URL_PRODUCTION_SL,
    VITE_BACKEND_URL_PRODUCTION_SL: process.env.VITE_BACKEND_URL_PRODUCTION_SL,
}